name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Make a change
      run: |
        echo $(date) > date.txt
        git config --global user.name 'realsubodh'
        git config --global user.email 'subodhsingh3477@gmail.com'
        git add date.txt
        git commit -m "Daily commit"

    - name: Push changes
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git push https://realsubodh:${{ secrets.PAT }}@github.com/realsubodh/daily-commit-repo.git
